{% set name = "mofapy" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4d17620ffb3bc1eadcb5f44945f427df06a5b0abad63fedfab875fc36d13afde

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed . 

requirements:
  host:
    - argparse
    - h5py
    - numpy
    - pandas
    - pip
    - python
    - scipy
    - sklearn
  run:
    - argparse
    - h5py
    - numpy
    - pandas
    - python
    - scipy
    - sklearn

test:
  imports:
    - mofapy
    - mofapy.core
    - mofapy.run

about:
  home: https://github.com/PMBio/MOFA
  license: MIT
  license_family: MIT
  summary: Multi-Omics Factor Analysis

extra:
  recipe-maintainers:
    - abotzki 
