{% set version = 'v.1.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-intlim
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://github.com/Mathelab/IntLIM/archive/{{ version }}.tar.gz
  sha256: b0ea63ec73a045037e1bfec035eda1f085f617fdfd339c69e9b4522e841ffe7d 

build:
  merge_build_host: True  # [win]

  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - bioconductor-multidataset
    - r-dendextend
    - r-dt
    - r-gplots
    - r-heatmaply
    - r-highcharter
    - r-rmarkdown
    - r-plotly
    - r-shinydashboard
    - r-shinyfiles
    - r-shinyjs

  run:
    - r-base
    - bioconductor-multidataset
    - r-dendextend
    - r-dt
    - r-gplots
    - r-heatmaply
    - r-highcharter
    - r-rmarkdown
    - r-shinyfiles
    - r-plotly
    - r-shinydashboard
    - r-shinyjs

test:
  commands:

    - $R -e "library('IntLIM')"           # [not win]
    - "\"%R%\" -e \"library('IntLIM')\""  # [win]

about:
  home: http://www.mixOmics.org
  license: GPL (>= 2)
  summary: 'Multivariate methods are well suited to large omics data sets where the number of
    with variants of multi-group Partial Least Squares.'

  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}\/lib\/R\/share\/licenses\/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
extra:
  container:
    # needed for libGL.so.1
    extended-base: true
  recipe-maintainers:
    - abotzki 
